sudo: required  # if use docker we have to have superuser permission in order to execute this build
services:
  - docker      # travis-ci will automatically install a copy of docker into the running container

before_install:
  - docker build -t dguo456/docker-react -f Dockerfile.dev .  # build image using Dockerfile.dev

script:
  - docker run dguo456/docker-react npm run test -- --coverage  # let travis-ci run test suite
